# 添加全局PID参数配置
# gazebo_ros_control:
#   pid_gains:
#     back_right_wheel_joint: {p: 100, i: 0.01, d: 10}
#     back_left_wheel_joint:  {p: 100, i: 0.01, d: 10}
#     front_left_wheel_joint: {p: 100, i: 0.01, d: 10}
#     front_right_wheel_joint: {p: 100, i: 0.01, d: 10}

# 直接定义控制器（移除robot_controller顶层键）
back_right_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: back_right_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

back_left_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: back_left_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

front_left_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: front_left_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

front_right_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: front_right_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 30